"""Add BaseEntity with auto-incrementing id

Revision ID: b162d3845568
Revises: 4ae9e88abf5f
Create Date: 2024-09-10 13:23:11.402622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b162d3845568'
down_revision: Union[str, None] = '4ae9e88abf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'mode',
               existing_type=postgresql.ENUM('PUBLIC', 'PRIVATE', 'NONPROFIT', name='companymode'),
               nullable=False)
    op.alter_column('company', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('company', 'mode',
               existing_type=postgresql.ENUM('PUBLIC', 'PRIVATE', 'NONPROFIT', name='companymode'),
               nullable=True)
    # ### end Alembic commands ###
